server:
  port: 8485

spring:
  profiles:
    active: production
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    date-format: YYYY-MM-dd
---

spring:
  config:
    activate:
      on-profile: dev
server:
  ssl:
    enabled: false


---

spring:
  config:
    activate:
      on-profile: production



